// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: api/proto/plant.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PlantService_GetPlantStatus_FullMethodName = "/plant.v1.PlantService/GetPlantStatus"
	PlantService_GetHistory_FullMethodName     = "/plant.v1.PlantService/GetHistory"
)

// PlantServiceClient is the client API for PlantService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PlantServiceClient interface {
	GetPlantStatus(ctx context.Context, in *GetPlantStatusRequest, opts ...grpc.CallOption) (*GetPlantStatusResponse, error)
	GetHistory(ctx context.Context, in *GetHistoryRequest, opts ...grpc.CallOption) (*GetHistoryResponse, error)
}

type plantServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPlantServiceClient(cc grpc.ClientConnInterface) PlantServiceClient {
	return &plantServiceClient{cc}
}

func (c *plantServiceClient) GetPlantStatus(ctx context.Context, in *GetPlantStatusRequest, opts ...grpc.CallOption) (*GetPlantStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPlantStatusResponse)
	err := c.cc.Invoke(ctx, PlantService_GetPlantStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plantServiceClient) GetHistory(ctx context.Context, in *GetHistoryRequest, opts ...grpc.CallOption) (*GetHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHistoryResponse)
	err := c.cc.Invoke(ctx, PlantService_GetHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlantServiceServer is the server API for PlantService service.
// All implementations must embed UnimplementedPlantServiceServer
// for forward compatibility.
type PlantServiceServer interface {
	GetPlantStatus(context.Context, *GetPlantStatusRequest) (*GetPlantStatusResponse, error)
	GetHistory(context.Context, *GetHistoryRequest) (*GetHistoryResponse, error)
	mustEmbedUnimplementedPlantServiceServer()
}

// UnimplementedPlantServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPlantServiceServer struct{}

func (UnimplementedPlantServiceServer) GetPlantStatus(context.Context, *GetPlantStatusRequest) (*GetPlantStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPlantStatus not implemented")
}
func (UnimplementedPlantServiceServer) GetHistory(context.Context, *GetHistoryRequest) (*GetHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHistory not implemented")
}
func (UnimplementedPlantServiceServer) mustEmbedUnimplementedPlantServiceServer() {}
func (UnimplementedPlantServiceServer) testEmbeddedByValue()                      {}

// UnsafePlantServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PlantServiceServer will
// result in compilation errors.
type UnsafePlantServiceServer interface {
	mustEmbedUnimplementedPlantServiceServer()
}

func RegisterPlantServiceServer(s grpc.ServiceRegistrar, srv PlantServiceServer) {
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PlantService_ServiceDesc, srv)
}

func _PlantService_GetPlantStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlantStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlantServiceServer).GetPlantStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlantService_GetPlantStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlantServiceServer).GetPlantStatus(ctx, req.(*GetPlantStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlantService_GetHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlantServiceServer).GetHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlantService_GetHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlantServiceServer).GetHistory(ctx, req.(*GetHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PlantService_ServiceDesc is the grpc.ServiceDesc for PlantService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PlantService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "plant.v1.PlantService",
	HandlerType: (*PlantServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPlantStatus",
			Handler:    _PlantService_GetPlantStatus_Handler,
		},
		{
			MethodName: "GetHistory",
			Handler:    _PlantService_GetHistory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/plant.proto",
}
