// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/proto/plant.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPlantStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlantStatusRequest) Reset() {
	*x = GetPlantStatusRequest{}
	mi := &file_api_proto_plant_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlantStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlantStatusRequest) ProtoMessage() {}

func (x *GetPlantStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plant_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*GetPlantStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_plant_proto_rawDescGZIP(), []int{0}
}

type GetPlantStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *PlantStatus           `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlantStatusResponse) Reset() {
	*x = GetPlantStatusResponse{}
	mi := &file_api_proto_plant_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlantStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlantStatusResponse) ProtoMessage() {}

func (x *GetPlantStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plant_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*GetPlantStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_plant_proto_rawDescGZIP(), []int{1}
}

func (x *GetPlantStatusResponse) GetStatus() *PlantStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type GetHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartTime     int64                  `protobuf:"varint,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       int64                  `protobuf:"varint,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryRequest) Reset() {
	*x = GetHistoryRequest{}
	mi := &file_api_proto_plant_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryRequest) ProtoMessage() {}

func (x *GetHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plant_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*GetHistoryRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_plant_proto_rawDescGZIP(), []int{2}
}

func (x *GetHistoryRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *GetHistoryRequest) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

type GetHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Points        []*HistoryPoint        `protobuf:"bytes,1,rep,name=points,proto3" json:"points,omitempty"`
	Trend         string                 `protobuf:"bytes,2,opt,name=trend,proto3" json:"trend,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryResponse) Reset() {
	*x = GetHistoryResponse{}
	mi := &file_api_proto_plant_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryResponse) ProtoMessage() {}

func (x *GetHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plant_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*GetHistoryResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_plant_proto_rawDescGZIP(), []int{3}
}

func (x *GetHistoryResponse) GetPoints() []*HistoryPoint {
	if x != nil {
		return x.Points
	}
	return nil
}

func (x *GetHistoryResponse) GetTrend() string {
	if x != nil {
		return x.Trend
	}
	return ""
}

type PlantStatus struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Recommendation string                 `protobuf:"bytes,1,opt,name=recommendation,proto3" json:"recommendation,omitempty"`
	LightCategory  string                 `protobuf:"bytes,2,opt,name=light_category,json=lightCategory,proto3" json:"light_category,omitempty"`
	CurrentLux     float64                `protobuf:"fixed64,3,opt,name=current_lux,json=currentLux,proto3" json:"current_lux,omitempty"`
	Trend          string                 `protobuf:"bytes,4,opt,name=trend,proto3" json:"trend,omitempty"`
	Timestamp      int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PlantStatus) Reset() {
	*x = PlantStatus{}
	mi := &file_api_proto_plant_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlantStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlantStatus) ProtoMessage() {}

func (x *PlantStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plant_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*PlantStatus) Descriptor() ([]byte, []int) {
	return file_api_proto_plant_proto_rawDescGZIP(), []int{4}
}

func (x *PlantStatus) GetRecommendation() string {
	if x != nil {
		return x.Recommendation
	}
	return ""
}

func (x *PlantStatus) GetLightCategory() string {
	if x != nil {
		return x.LightCategory
	}
	return ""
}

func (x *PlantStatus) GetCurrentLux() float64 {
	if x != nil {
		return x.CurrentLux
	}
	return 0
}

func (x *PlantStatus) GetTrend() string {
	if x != nil {
		return x.Trend
	}
	return ""
}

func (x *PlantStatus) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type HistoryPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Lux           float64                `protobuf:"fixed64,2,opt,name=lux,proto3" json:"lux,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryPoint) Reset() {
	*x = HistoryPoint{}
	mi := &file_api_proto_plant_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryPoint) ProtoMessage() {}

func (x *HistoryPoint) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plant_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*HistoryPoint) Descriptor() ([]byte, []int) {
	return file_api_proto_plant_proto_rawDescGZIP(), []int{5}
}

func (x *HistoryPoint) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *HistoryPoint) GetLux() float64 {
	if x != nil {
		return x.Lux
	}
	return 0
}

func (x *HistoryPoint) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

var File_api_proto_plant_proto protoreflect.FileDescriptor

const file_api_proto_plant_proto_rawDesc = "" +
	"\n\x15api/proto/plant.proto\x12\bplant.v1\"\x17\n\x15GetPlantStatusRequest\"G\n\x16GetPlantStatusResponse\x12-\n\x06status\x18\x01 \x01(\v2\x15.plant.v1.PlantStatusR\x06status\"M\n\x11GetHistoryRequest\x12\x1d\n\nstart_time\x18\x01 \x01(\x03R\tstartTime\x12\x19\n\bend_time\x18\x02 \x01(\x03R\aendTime\"Z\n\x12GetHistoryResponse\x12.\n\x06points\x18\x01 \x03(\v2\x16.plant.v1.HistoryPointR\x06points\x12\x14\n\x05trend\x18\x02 \x01(\tR\x05trend\"\xb1\x01\n\vPlantStatus\x12&\n\x0erecommendation\x18\x01 \x01(\tR\x0erecommendation\x12%\n\x0elight_category\x18\x02 \x01(\tR\rlightCategory\x12\x1f\n\vcurrent_lux\x18\x03 \x01(\x01R\ncurrentLux\x12\x14\n\x05trend\x18\x04 \x01(\tR\x05trend\x12\x1c\n\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\"Z\n\fHistoryPoint\x12\x1c\n\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x10\n\x03lux\x18\x02 \x01(\x01R\x03lux\x12\x1a\n\bcategory\x18\x03 \x01(\tR\bcategory2\xac\x01\n\fPlantService\x12S\n\x0eGetPlantStatus\x12\x1f.plant.v1.GetPlantStatusRequest\x1a .plant.v1.GetPlantStatusResponse\x12G\n\nGetHistory\x12\x1b.plant.v1.GetHistoryRequest\x1a\x1c.plant.v1.GetHistoryResponseBBZ@github.com/quentinrf/plant-monitor/services/plant-service/pkg/pbb\x06proto3"

var (
	file_api_proto_plant_proto_rawDescOnce sync.Once
	file_api_proto_plant_proto_rawDescData []byte
)

func file_api_proto_plant_proto_rawDescGZIP() []byte {
	file_api_proto_plant_proto_rawDescOnce.Do(func() {
		file_api_proto_plant_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_plant_proto_rawDesc), len(file_api_proto_plant_proto_rawDesc)))
	})
	return file_api_proto_plant_proto_rawDescData
}

var file_api_proto_plant_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_proto_plant_proto_goTypes = []any{
	(*GetPlantStatusRequest)(nil),  // 0: plant.v1.GetPlantStatusRequest
	(*GetPlantStatusResponse)(nil), // 1: plant.v1.GetPlantStatusResponse
	(*GetHistoryRequest)(nil),      // 2: plant.v1.GetHistoryRequest
	(*GetHistoryResponse)(nil),     // 3: plant.v1.GetHistoryResponse
	(*PlantStatus)(nil),            // 4: plant.v1.PlantStatus
	(*HistoryPoint)(nil),           // 5: plant.v1.HistoryPoint
}
var file_api_proto_plant_proto_depIdxs = []int32{
	4, // 0: plant.v1.GetPlantStatusResponse.status:type_name -> plant.v1.PlantStatus
	5, // 1: plant.v1.GetHistoryResponse.points:type_name -> plant.v1.HistoryPoint
	0, // 2: plant.v1.PlantService.GetPlantStatus:input_type -> plant.v1.GetPlantStatusRequest
	2, // 3: plant.v1.PlantService.GetHistory:input_type -> plant.v1.GetHistoryRequest
	1, // 4: plant.v1.PlantService.GetPlantStatus:output_type -> plant.v1.GetPlantStatusResponse
	3, // 5: plant.v1.PlantService.GetHistory:output_type -> plant.v1.GetHistoryResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_proto_plant_proto_init() }
func file_api_proto_plant_proto_init() {
	if File_api_proto_plant_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_plant_proto_rawDesc), len(file_api_proto_plant_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_plant_proto_goTypes,
		DependencyIndexes: file_api_proto_plant_proto_depIdxs,
		MessageInfos:      file_api_proto_plant_proto_msgTypes,
	}.Build()
	File_api_proto_plant_proto = out.File
	file_api_proto_plant_proto_goTypes = nil
	file_api_proto_plant_proto_depIdxs = nil
}
