// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: api/proto/light.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LightService_GetCurrentLight_FullMethodName = "/light.v1.LightService/GetCurrentLight"
	LightService_GetHistory_FullMethodName      = "/light.v1.LightService/GetHistory"
	LightService_RecordReading_FullMethodName   = "/light.v1.LightService/RecordReading"
)

// LightServiceClient is the client API for LightService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// LightService provides light monitoring capabilities
type LightServiceClient interface {
	// GetCurrentLight returns the most recent light reading
	GetCurrentLight(ctx context.Context, in *GetCurrentLightRequest, opts ...grpc.CallOption) (*GetCurrentLightResponse, error)
	// GetHistory returns light readings within a time range
	GetHistory(ctx context.Context, in *GetHistoryRequest, opts ...grpc.CallOption) (*GetHistoryResponse, error)
	// RecordReading manually records a light reading (for testing)
	RecordReading(ctx context.Context, in *RecordReadingRequest, opts ...grpc.CallOption) (*RecordReadingResponse, error)
}

type lightServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLightServiceClient(cc grpc.ClientConnInterface) LightServiceClient {
	return &lightServiceClient{cc}
}

func (c *lightServiceClient) GetCurrentLight(ctx context.Context, in *GetCurrentLightRequest, opts ...grpc.CallOption) (*GetCurrentLightResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCurrentLightResponse)
	err := c.cc.Invoke(ctx, LightService_GetCurrentLight_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lightServiceClient) GetHistory(ctx context.Context, in *GetHistoryRequest, opts ...grpc.CallOption) (*GetHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHistoryResponse)
	err := c.cc.Invoke(ctx, LightService_GetHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lightServiceClient) RecordReading(ctx context.Context, in *RecordReadingRequest, opts ...grpc.CallOption) (*RecordReadingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordReadingResponse)
	err := c.cc.Invoke(ctx, LightService_RecordReading_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LightServiceServer is the server API for LightService service.
// All implementations must embed UnimplementedLightServiceServer
// for forward compatibility.
//
// LightService provides light monitoring capabilities
type LightServiceServer interface {
	// GetCurrentLight returns the most recent light reading
	GetCurrentLight(context.Context, *GetCurrentLightRequest) (*GetCurrentLightResponse, error)
	// GetHistory returns light readings within a time range
	GetHistory(context.Context, *GetHistoryRequest) (*GetHistoryResponse, error)
	// RecordReading manually records a light reading (for testing)
	RecordReading(context.Context, *RecordReadingRequest) (*RecordReadingResponse, error)
	mustEmbedUnimplementedLightServiceServer()
}

// UnimplementedLightServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLightServiceServer struct{}

func (UnimplementedLightServiceServer) GetCurrentLight(context.Context, *GetCurrentLightRequest) (*GetCurrentLightResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCurrentLight not implemented")
}
func (UnimplementedLightServiceServer) GetHistory(context.Context, *GetHistoryRequest) (*GetHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHistory not implemented")
}
func (UnimplementedLightServiceServer) RecordReading(context.Context, *RecordReadingRequest) (*RecordReadingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RecordReading not implemented")
}
func (UnimplementedLightServiceServer) mustEmbedUnimplementedLightServiceServer() {}
func (UnimplementedLightServiceServer) testEmbeddedByValue()                      {}

// UnsafeLightServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LightServiceServer will
// result in compilation errors.
type UnsafeLightServiceServer interface {
	mustEmbedUnimplementedLightServiceServer()
}

func RegisterLightServiceServer(s grpc.ServiceRegistrar, srv LightServiceServer) {
	// If the following call panics, it indicates UnimplementedLightServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LightService_ServiceDesc, srv)
}

func _LightService_GetCurrentLight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCurrentLightRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LightServiceServer).GetCurrentLight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LightService_GetCurrentLight_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LightServiceServer).GetCurrentLight(ctx, req.(*GetCurrentLightRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LightService_GetHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LightServiceServer).GetHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LightService_GetHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LightServiceServer).GetHistory(ctx, req.(*GetHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LightService_RecordReading_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordReadingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LightServiceServer).RecordReading(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LightService_RecordReading_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LightServiceServer).RecordReading(ctx, req.(*RecordReadingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LightService_ServiceDesc is the grpc.ServiceDesc for LightService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LightService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "light.v1.LightService",
	HandlerType: (*LightServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCurrentLight",
			Handler:    _LightService_GetCurrentLight_Handler,
		},
		{
			MethodName: "GetHistory",
			Handler:    _LightService_GetHistory_Handler,
		},
		{
			MethodName: "RecordReading",
			Handler:    _LightService_RecordReading_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/light.proto",
}
