// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/proto/light.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCurrentLightRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentLightRequest) Reset() {
	*x = GetCurrentLightRequest{}
	mi := &file_api_proto_light_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentLightRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentLightRequest) ProtoMessage() {}

func (x *GetCurrentLightRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_light_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentLightRequest.ProtoReflect.Descriptor instead.
func (*GetCurrentLightRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_light_proto_rawDescGZIP(), []int{0}
}

type GetCurrentLightResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reading       *LightReading          `protobuf:"bytes,1,opt,name=reading,proto3" json:"reading,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentLightResponse) Reset() {
	*x = GetCurrentLightResponse{}
	mi := &file_api_proto_light_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentLightResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentLightResponse) ProtoMessage() {}

func (x *GetCurrentLightResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_light_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentLightResponse.ProtoReflect.Descriptor instead.
func (*GetCurrentLightResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_light_proto_rawDescGZIP(), []int{1}
}

func (x *GetCurrentLightResponse) GetReading() *LightReading {
	if x != nil {
		return x.Reading
	}
	return nil
}

type GetHistoryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Start of time range (Unix timestamp)
	StartTime int64 `protobuf:"varint,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// End of time range (Unix timestamp)
	EndTime       int64 `protobuf:"varint,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryRequest) Reset() {
	*x = GetHistoryRequest{}
	mi := &file_api_proto_light_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryRequest) ProtoMessage() {}

func (x *GetHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_light_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetHistoryRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_light_proto_rawDescGZIP(), []int{2}
}

func (x *GetHistoryRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *GetHistoryRequest) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

type GetHistoryResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Readings []*LightReading        `protobuf:"bytes,1,rep,name=readings,proto3" json:"readings,omitempty"`
	// Statistics
	AverageLux    float64 `protobuf:"fixed64,2,opt,name=average_lux,json=averageLux,proto3" json:"average_lux,omitempty"`
	MinLux        float64 `protobuf:"fixed64,3,opt,name=min_lux,json=minLux,proto3" json:"min_lux,omitempty"`
	MaxLux        float64 `protobuf:"fixed64,4,opt,name=max_lux,json=maxLux,proto3" json:"max_lux,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryResponse) Reset() {
	*x = GetHistoryResponse{}
	mi := &file_api_proto_light_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryResponse) ProtoMessage() {}

func (x *GetHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_light_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetHistoryResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_light_proto_rawDescGZIP(), []int{3}
}

func (x *GetHistoryResponse) GetReadings() []*LightReading {
	if x != nil {
		return x.Readings
	}
	return nil
}

func (x *GetHistoryResponse) GetAverageLux() float64 {
	if x != nil {
		return x.AverageLux
	}
	return 0
}

func (x *GetHistoryResponse) GetMinLux() float64 {
	if x != nil {
		return x.MinLux
	}
	return 0
}

func (x *GetHistoryResponse) GetMaxLux() float64 {
	if x != nil {
		return x.MaxLux
	}
	return 0
}

type RecordReadingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lux           float64                `protobuf:"fixed64,1,opt,name=lux,proto3" json:"lux,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordReadingRequest) Reset() {
	*x = RecordReadingRequest{}
	mi := &file_api_proto_light_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordReadingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordReadingRequest) ProtoMessage() {}

func (x *RecordReadingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_light_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordReadingRequest.ProtoReflect.Descriptor instead.
func (*RecordReadingRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_light_proto_rawDescGZIP(), []int{4}
}

func (x *RecordReadingRequest) GetLux() float64 {
	if x != nil {
		return x.Lux
	}
	return 0
}

type RecordReadingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reading       *LightReading          `protobuf:"bytes,1,opt,name=reading,proto3" json:"reading,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordReadingResponse) Reset() {
	*x = RecordReadingResponse{}
	mi := &file_api_proto_light_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordReadingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordReadingResponse) ProtoMessage() {}

func (x *RecordReadingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_light_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordReadingResponse.ProtoReflect.Descriptor instead.
func (*RecordReadingResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_light_proto_rawDescGZIP(), []int{5}
}

func (x *RecordReadingResponse) GetReading() *LightReading {
	if x != nil {
		return x.Reading
	}
	return nil
}

type LightReading struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Lux           float64                `protobuf:"fixed64,2,opt,name=lux,proto3" json:"lux,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Unix timestamp
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`    // "Low Light", "Medium Light", "High Light"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LightReading) Reset() {
	*x = LightReading{}
	mi := &file_api_proto_light_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LightReading) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LightReading) ProtoMessage() {}

func (x *LightReading) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_light_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LightReading.ProtoReflect.Descriptor instead.
func (*LightReading) Descriptor() ([]byte, []int) {
	return file_api_proto_light_proto_rawDescGZIP(), []int{6}
}

func (x *LightReading) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LightReading) GetLux() float64 {
	if x != nil {
		return x.Lux
	}
	return 0
}

func (x *LightReading) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *LightReading) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

var File_api_proto_light_proto protoreflect.FileDescriptor

const file_api_proto_light_proto_rawDesc = "" +
	"\n" +
	"\x15api/proto/light.proto\x12\blight.v1\"\x18\n" +
	"\x16GetCurrentLightRequest\"K\n" +
	"\x17GetCurrentLightResponse\x120\n" +
	"\areading\x18\x01 \x01(\v2\x16.light.v1.LightReadingR\areading\"M\n" +
	"\x11GetHistoryRequest\x12\x1d\n" +
	"\n" +
	"start_time\x18\x01 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x02 \x01(\x03R\aendTime\"\x9b\x01\n" +
	"\x12GetHistoryResponse\x122\n" +
	"\breadings\x18\x01 \x03(\v2\x16.light.v1.LightReadingR\breadings\x12\x1f\n" +
	"\vaverage_lux\x18\x02 \x01(\x01R\n" +
	"averageLux\x12\x17\n" +
	"\amin_lux\x18\x03 \x01(\x01R\x06minLux\x12\x17\n" +
	"\amax_lux\x18\x04 \x01(\x01R\x06maxLux\"(\n" +
	"\x14RecordReadingRequest\x12\x10\n" +
	"\x03lux\x18\x01 \x01(\x01R\x03lux\"I\n" +
	"\x15RecordReadingResponse\x120\n" +
	"\areading\x18\x01 \x01(\v2\x16.light.v1.LightReadingR\areading\"j\n" +
	"\fLightReading\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x10\n" +
	"\x03lux\x18\x02 \x01(\x01R\x03lux\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory2\x81\x02\n" +
	"\fLightService\x12V\n" +
	"\x0fGetCurrentLight\x12 .light.v1.GetCurrentLightRequest\x1a!.light.v1.GetCurrentLightResponse\x12G\n" +
	"\n" +
	"GetHistory\x12\x1b.light.v1.GetHistoryRequest\x1a\x1c.light.v1.GetHistoryResponse\x12P\n" +
	"\rRecordReading\x12\x1e.light.v1.RecordReadingRequest\x1a\x1f.light.v1.RecordReadingResponseBBZ@github.com/quentinrf/plant-monitor/services/light-service/pkg/pbb\x06proto3"

var (
	file_api_proto_light_proto_rawDescOnce sync.Once
	file_api_proto_light_proto_rawDescData []byte
)

func file_api_proto_light_proto_rawDescGZIP() []byte {
	file_api_proto_light_proto_rawDescOnce.Do(func() {
		file_api_proto_light_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_light_proto_rawDesc), len(file_api_proto_light_proto_rawDesc)))
	})
	return file_api_proto_light_proto_rawDescData
}

var file_api_proto_light_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_proto_light_proto_goTypes = []any{
	(*GetCurrentLightRequest)(nil),  // 0: light.v1.GetCurrentLightRequest
	(*GetCurrentLightResponse)(nil), // 1: light.v1.GetCurrentLightResponse
	(*GetHistoryRequest)(nil),       // 2: light.v1.GetHistoryRequest
	(*GetHistoryResponse)(nil),      // 3: light.v1.GetHistoryResponse
	(*RecordReadingRequest)(nil),    // 4: light.v1.RecordReadingRequest
	(*RecordReadingResponse)(nil),   // 5: light.v1.RecordReadingResponse
	(*LightReading)(nil),            // 6: light.v1.LightReading
}
var file_api_proto_light_proto_depIdxs = []int32{
	6, // 0: light.v1.GetCurrentLightResponse.reading:type_name -> light.v1.LightReading
	6, // 1: light.v1.GetHistoryResponse.readings:type_name -> light.v1.LightReading
	6, // 2: light.v1.RecordReadingResponse.reading:type_name -> light.v1.LightReading
	0, // 3: light.v1.LightService.GetCurrentLight:input_type -> light.v1.GetCurrentLightRequest
	2, // 4: light.v1.LightService.GetHistory:input_type -> light.v1.GetHistoryRequest
	4, // 5: light.v1.LightService.RecordReading:input_type -> light.v1.RecordReadingRequest
	1, // 6: light.v1.LightService.GetCurrentLight:output_type -> light.v1.GetCurrentLightResponse
	3, // 7: light.v1.LightService.GetHistory:output_type -> light.v1.GetHistoryResponse
	5, // 8: light.v1.LightService.RecordReading:output_type -> light.v1.RecordReadingResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_proto_light_proto_init() }
func file_api_proto_light_proto_init() {
	if File_api_proto_light_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_light_proto_rawDesc), len(file_api_proto_light_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_light_proto_goTypes,
		DependencyIndexes: file_api_proto_light_proto_depIdxs,
		MessageInfos:      file_api_proto_light_proto_msgTypes,
	}.Build()
	File_api_proto_light_proto = out.File
	file_api_proto_light_proto_goTypes = nil
	file_api_proto_light_proto_depIdxs = nil
}
